version: '3.8'

services:
  backend:
    build: ./backend
    container_name: email-api
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: email-ui
    ports:
      - "4200:80"
    depends_on:
      - backend